repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        name: Flake8
        description: This hook runs flake8.
        entry: flake8
        language: python
        types: [python]
        additional_dependencies: [flake8-alfred]
    -   id: check-yaml
        name: Check Yaml
        description: This hook checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]